version: '3.7'
services:
  root-service:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      # Mounts development code inside the container.
      - ..:/workspace:cached
      # Mount host machine .gitconfig file inside the container.
      - ~/.gitconfig:/root/.gitconfig
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity